import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create schema auth;create role authenticated;create type public.user_role as enum('autor','editor');
create function auth.uid() returns uuid language sql stable as $$ select '00000000-0000-0000-0000-000000000001'::uuid $$;
create table public.profiles(id uuid,role public.user_role,areas_asignadas text[]);
insert into public.profiles values(auth.uid(),'autor',array['Alimentos']);
create function public.current_role_name() returns public.user_role language sql stable security definer as $$ select role from profiles where id=auth.uid() $$;
create function public.current_user_areas() returns text[] language sql stable security definer as $$ select areas_asignadas from profiles where id=auth.uid() $$;
create table public.manuscripts(folio text unique,autor_correspondencia_id uuid);
insert into public.manuscripts values('RCIA-007-2026',auth.uid());
create sequence public.manuscript_folio_seq start 7;
alter table public.manuscripts enable row level security;
create policy own_read on public.manuscripts for select using(public.current_role_name()='autor' and autor_correspondencia_id=auth.uid());
create policy own_insert on public.manuscripts for insert with check(autor_correspondencia_id=auth.uid());
grant usage on schema public,auth to authenticated;
grant select,insert on public.manuscripts to authenticated;grant usage on public.manuscript_folio_seq to authenticated;`);
const folios=readFileSync('schema_fase5_folios.sql','utf8');
await db.exec(folios.slice(folios.indexOf('create or replace function public.generar_folio()'),folios.indexOf('-- RESTART')));
await db.exec(`create trigger folio before insert on public.manuscripts for each row when(new.folio is null) execute function public.generar_folio();set role authenticated;set search_path='';`);
await assert.rejects(db.exec('insert into public.manuscripts(autor_correspondencia_id) values(auth.uid())'),e=>e.message.includes('relation "profiles" does not exist'));
await db.exec('reset role;set search_path=public');
await db.exec(readFileSync('schema_fase6_corregir_perfiles.sql','utf8').replace(/^\uFEFF/,''));
await db.exec('set role authenticated');
const r=await db.query('insert into public.manuscripts(autor_correspondencia_id) values(auth.uid()) returning folio');
assert.match(r.rows[0].folio,/^RCIA-\d{3}-\d{4}$/);
await db.exec("set search_path=''");
assert.equal((await db.query('select public.current_role_name() as role')).rows[0].role,'autor');
assert.deepEqual((await db.query('select public.current_user_areas() as areas')).rows[0].areas,['Alimentos']);
console.log('OK: reproducido el error profiles; corregido envío con RLS y generador de folio; roles y áreas funcionan con search_path vacío.');
await db.close();

